# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biaoqing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('unc', models.CharField(max_length=10)),
                ('seq', models.IntegerField()),
            ],
        ),
    ]
