# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dafeiji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxoid', models.TextField()),
                ('enflight', models.TextField(default='')),
                ('myflight', models.TextField(default='')),
                ('fires', models.TextField(default='[]')),
                ('win', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxoid', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('best', models.IntegerField(default=999)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dafeiji.Battle')),
            ],
        ),
    ]
