# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dafeiji', '0002_battle_pilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='fires',
            field=models.TextField(default='{}'),
        ),
    ]
