# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('enemy_type', models.IntegerField(default=100, max_length=3)),
                ('level', models.IntegerField(default=1, max_length=5)),
                ('hp', models.IntegerField(default=10, max_length=10)),
                ('damage', models.IntegerField(default=0, max_length=10)),
                ('desc', models.TextField(default=b'default description.')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0, max_length=10)),
                ('class_name', models.CharField(max_length=100)),
                ('desc', models.TextField(default=b'default description.')),
                ('item_type', models.CharField(max_length=100)),
                ('extra_params', models.TextField(default=b'{}')),
                ('level', models.IntegerField(default=1, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'DefaultMap', max_length=100)),
                ('desc', models.TextField(default=b'default map description.')),
                ('level', models.IntegerField(default=1, max_length=5)),
                ('enter', models.TextField(default=b'{}')),
                ('wxoid', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxoid', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('money', models.IntegerField(default=33, max_length=10)),
                ('hp', models.IntegerField(default=100, max_length=10)),
                ('level', models.IntegerField(default=1, max_length=5)),
                ('exp', models.IntegerField(default=1, max_length=11)),
                ('victory', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0, max_length=3)),
                ('location_x', models.IntegerField(default=0, max_length=5)),
                ('location_y', models.IntegerField(default=0, max_length=5)),
                ('inventory', models.TextField(default=b'{}')),
                ('souls', models.IntegerField(default=0, max_length=11)),
                ('dienum', models.IntegerField(default=0, max_length=11)),
                ('last_action', models.CharField(default=b'h', max_length=100)),
                ('inmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='txtadventure.Maps')),
            ],
        ),
        migrations.CreateModel(
            name='Tiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0, max_length=11)),
                ('y', models.IntegerField(default=0, max_length=11)),
                ('accy', models.TextField(default=b'{}')),
                ('n', models.BooleanField(default=False)),
                ('s', models.BooleanField(default=False)),
                ('e', models.BooleanField(default=False)),
                ('w', models.BooleanField(default=False)),
                ('desc', models.TextField(default=b'')),
                ('inmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='txtadventure.Maps')),
            ],
        ),
    ]
