# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txtadventure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemies',
            name='damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemies',
            name='enemy_type',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='enemies',
            name='hp',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='enemies',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='items',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='items',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maps',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='dienum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='exp',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='location_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='location_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=33),
        ),
        migrations.AlterField(
            model_name='player',
            name='souls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tiles',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tiles',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
